import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Layout } from './components/Layout'
import { Toaster } from 'react-hot-toast'
import { getServerSession } from 'next-auth'
import { SessionProvider } from './context/SessionProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: React.ReactNode
}

export default async function RootLayout(props: LayoutProps) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <SessionProvider session={session}>
        <body className={inter.className}>
          <Toaster />
          <Layout>
            {props.children}
          </Layout>
        </body>
      </SessionProvider>
    </html>
  )
}
