import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Sidebar } from './components/Sidebar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: React.ReactNode
}

export default function RootLayout(props: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="h-full bg-black">
          <div className="container mx-auto h-full xl:px-30 max-w-6xl">
            <div className="grid grid-cols-4 h-full">
              <Sidebar />
              <div className="col-span-3 lg:col-span-2 border-x-[1px] border-neutral-800">
                {props.children}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  )
}
