import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Layout } from './components/Layout'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type LayoutProps = {
  children: React.ReactNode
}

export default function RootLayout(props: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout />
      </body>
    </html>
  )
}
